### ISSUE TITLE
{ cata classic } carbonite not show gathering nodes in cata new areas

### ISSUE THREAD

**Issue by dare2010** [IrcDirk/Carbonite-Classic#367]
**hi,
can't show herb/mining nodes in cata grounds.
i've imported nodes from gathermater2 data but still miss new herb and mining
i've deleted and reintalled the addon, deleted all nodes and imported again.
in the guide  & gather menu > herbalism or mining it miss the new herbs and mining such as twilight jasmine, cinderbloom, elementium, etc**
"all other nodes and old areas work just fine"

**Comment by IrcDirk** [comment]
Forgot about one thing, im not at home. Ill fix that tommorow.

**Comment by IrcDirk** [comment]
Fixed... but some ores might be missing... im working on that.

**Comment by dare2010** [comment]
> Fixed... but some ores might be missing... im working on that.

yeah it worked fine.
but there is a broblem with gathermate2 data itself, there is not much nodes in cataclysm new areas, i've found a solution on the internet to copy data files from retail folder to the classic one and it worked just fine, all nodes are there but carbonite can't copy them

**Comment by IrcDirk** [comment]
Yes, Carbonite cant import Retail GatherMate2 data. I'm working on conversion.

**Comment by dare2010** [comment]
still a problem with gathermate2 data even after its updated,  now can have all nodes withough copying any files.
i've deleted all 3 addons gathermate2 and data + carbonite, tryed to import from gathermate2 data but it doesn't copy everything
![image](https://github.com/IrcDirk/Carbonite-Classic/assets/83879595/0bdd5ee6-d563-4cb2-9887-2abb1c34f8bf)
![image](https://github.com/IrcDirk/Carbonite-Classic/assets/83879595/a855cc48-afcd-4260-adb9-629edba13f9f)

**Comment by IrcDirk** [comment]
Carbonite GahterMate2 Data is based on **GatherMate2 Data Wowhead classic** and data in this mod is a MESS! 

Thats why im working on conversion from GaterMate2 Data **RETAIL** as i mentioned earlier.

**Comment by IrcDirk** [comment]
Updated now it should be better :)

**Comment by dare2010** [comment]
> Updated now it should be better :) (remember to delete old nodes and reimport new data)

yeah it worked  like magic, thx man :D
