### ISSUE TITLE
Auto scale icon stays fully opaque

### ISSUE THREAD

**Issue by dalesnail** [IrcDirk/Carbonite-Classic#67]
Auto scale icon stays fully opaque when not being moused over. I noticed all other icons and the surrounding frame fade out, but just this icon does not. Small thing, but triggers my ocd a little haha. 

![Map icon](https://user-images.githubusercontent.com/20726565/65837662-30b4c280-e2c8-11e9-954a-62f0736ea9f5.png)

**Comment by IrcDirk** [comment]
Right, Will fix it.

**Comment by dalesnail** [comment]
So the icon is now transparent, but now my entire minimap is transparent and drawn over icons. Tried changing the options for both of these with no luck so far. Will reinstall and edit if anything changes. 

![image](https://user-images.githubusercontent.com/20726565/65922804-97afa580-e3b4-11e9-8f2e-80f593a5b79a.png)

**Comment by IrcDirk** [comment]
Set Right click > transparency > fade out transparency

**Comment by dalesnail** [comment]
Well shoot, thank you haha, I originally tried that, but it didnt change right away so I thought it wasn't going to work. Tried it this time, and closed the menu and it changed back. 

So I still can't see the icons though. They seem to be under the minimap, but I dont have the "Minimap is drawn above icons" option chosen. I could just be missing a setting again though, sorry if so.

**Comment by IrcDirk** [comment]
It was fixed this way becouse of issue #65 so if window sould be transparent then all on map should be transparent... Or am i wrong?

**Comment by dalesnail** [comment]
I think I may just be referring to different icons? The one's I mean are the ones circled below. When I have the map minimized and it reverts to being a minimap, these icons no longer show, so it's just a minimap with no player icon or directional icon. I can still see nodes on it though, but that is all. 

This could be a whole other issue, I just thought it may have been a consequence of the changes to my issue and #65 

![2019_10_01_08_21_24_65837662_30b4c280_e2c8_11e9_954a_62f0736ea9f5 png_316_295_](https://user-images.githubusercontent.com/20726565/65961498-bcdbfc80-e424-11e9-8fad-a53687c935fc.png)

(Also side note here, feel free to remove, but I was thinking it might be helpful to start a carbonite discord if you're interested.)

**Comment by IrcDirk** [comment]
Those locations icons (the one in right top corner) are now hidden and should stay hidden when carbonite is on. 

Player arrowy icon hides when mouse outs carbonite map. I think ill add option to keep it showed when player wants.

**Comment by dalesnail** [comment]
Ah gotcha, I understand the direction one as we do have the tracker hud, so no biggy there, as it's more clean. 

The player icon doesn't seem to pop up even on mouseover for me though. The icon shows on the fullsize map, but not the minimap. Makes it a bit difficult to walk to nodes and stuff showing on the minimap when minimized to the top right.

**Comment by IrcDirk** [comment]
Will fix player icon on minimap.

**Comment by IrcDirk** [comment]
As to discord... hmmm dont know... do we need it?

**Comment by dalesnail** [comment]
Maybe not, but Carbonite is a very large and daunting addon for newcomers and people who haven't used it in a very long time. 

I just think it would be beneficial to have a discord for small issues that may just be option related, and are not bugs, that way if you, me, or someone else knows how to resolve an issue, it could be addressed right away. Plus I think it would just be a good place to give feedback if enough people that use the addon join.

**Comment by IrcDirk** [comment]
Still reporting issues should go to GitHub. I think about it. It could be good for community.

**Comment by dalesnail** [comment]
Oh I agree, I was just talking more about like one of my problems above. 

Like I thought that it was a bug that my minimap was showing transparent, but you showed me I just didn't have an option set right. 

Would be good for cummunity for sure.

**Comment by IrcDirk** [comment]
Now minimap player icon will not hide when mouseout Carb map.
